# Generated by Django 3.2.7 on 2021-09-07 09:20

from django.db import migrations, models
import register.validators


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[register.validators.validate_CNPJ], verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[register.validators.validate_CPF], verbose_name='CPF'),
        ),
    ]
