# Generated by Django 3.2.7 on 2021-09-07 09:49

from django.db import migrations, models
import register.validators


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210907_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[register.validators.validate_CNPJ], verbose_name='CNPJ'),
        ),
    ]
