# Generated by Django 3.2.7 on 2021-09-07 14:08

from django.db import migrations, models
import register.validators


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210907_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[register.validators.validate_CNPJ, register.validators.valida_cnpj], verbose_name='CNPJ'),
        ),
    ]
