# Generated by Django 3.2.7 on 2021-09-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_client_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='document',
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='meusarquivos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.client')),
            ],
        ),
    ]
