# Generated by Django 3.2.7 on 2021-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210908_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.FileField(null=True, upload_to='meusarquivos'),
        ),
        migrations.DeleteModel(
            name='Docs',
        ),
    ]
