# Generated by Django 3.2.7 on 2021-09-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20210909_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
